package bgp

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"sync"

	"tunneltug/anycast/config"
)

// BirdBackend rewrites a BIRD include file with static routes and runs birdc configure.
type BirdBackend struct {
	includePath string
	birdc       string
	protocol    string
	mu          sync.Mutex
}

func NewBirdBackend(cfg config.BirdConfig) *BirdBackend {
	return &BirdBackend{
		includePath: cfg.IncludePath,
		birdc:       cfg.Birdc,
		protocol:    cfg.Protocol,
	}
}

func (b *BirdBackend) Name() string { return "bird" }

func (b *BirdBackend) Announce(routes []Route) error {
	return b.apply(routes, true)
}

func (b *BirdBackend) Withdraw(routes []Route) error {
	return b.apply(routes, false)
}

func (b *BirdBackend) apply(routes []Route, announce bool) error {
	b.mu.Lock()
	defer b.mu.Unlock()

	body := b.render(routes, announce)
	if err := os.MkdirAll(filepath.Dir(b.includePath), 0o755); err != nil {
		return fmt.Errorf("bird mkdir: %w", err)
	}
	tmp := b.includePath + ".tmp"
	if err := os.WriteFile(tmp, []byte(body), 0o640); err != nil {
		return fmt.Errorf("bird write: %w", err)
	}
	if err := os.Rename(tmp, b.includePath); err != nil {
		return fmt.Errorf("bird rename: %w", err)
	}

	// Reload BIRD config. Failures are reported so the updater can retry.
	cmd := exec.Command(b.birdc, "configure")
	out, err := cmd.CombinedOutput()
	if err != nil {
		return fmt.Errorf("birdc configure: %w (%s)", err, strings.TrimSpace(string(out)))
	}
	return nil
}

func (b *BirdBackend) render(routes []Route, announce bool) string {
	var bld strings.Builder
	bld.WriteString("# Generated by tunneltug anycast — do not edit by hand\n")
	fmt.Fprintf(&bld, "# protocol filter target: %s\n", b.protocol)
	bld.WriteString("# ROV/BGPsec: signatures produced in-process by TunnelTug; inject into BGP speaker as configured.\n")
	if !announce || len(routes) == 0 {
		bld.WriteString("# no anycast routes (withdrawn / unhealthy)\n")
		return bld.String()
	}
	for _, r := range routes {
		// BIRD 2 static route syntax (data plane next-hop).
		fmt.Fprintf(&bld, "route %s via %s;\n", r.Prefix, r.NextHop)
		if r.BGPsec != nil {
			fmt.Fprintf(&bld, "# bgpsec %s ski=%x sig_len=%d target_asn=%d\n",
				r.Prefix, r.BGPsec.SKI, len(r.BGPsec.Signature), r.BGPsec.TargetASN)
		}
		if r.ROVState != "" {
			fmt.Fprintf(&bld, "# rov %s %s\n", r.Prefix, r.ROVState)
		}
	}
	return bld.String()
}

func (b *BirdBackend) Close() error { return nil }
